{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    mkIf
    mkOption
    optionalString
    types
    ;

  cfg = config.dusk.system.nixos.desktop.hyprland;
  hyprlandPkgs = inputs.hyprland.packages.${pkgs.system};

  launchTerm = cmd: "${pkgs.ghostty}/bin/ghostty --class=com.mitchellh.ghostty.floating -e ${cmd}";
  launchWeb =
    url: name: class:
    ''${pkgs.chromium}/bin/chromium --new-window --ozone-platform="wayland" --app="${url}" --name="${name}" --class="${class}"'';

  luaConfig = ''
    -- Generated by Nix: system/hyprland/hyprland.nix
    -- See https://wiki.hypr.land/Configuring/Start/ for the new Lua syntax.

    local mod = "SUPER"

    hl.config({
      general = {
        gaps_in     = 8,
        gaps_out    = 24,
        border_size = 3,
      },

      decoration = {
        inactive_opacity   = 0.90,
        fullscreen_opacity = 1.0,
        rounding           = 8,
        blur = {
          enabled = true,
          size    = 8,
          passes  = 2,
        },
      },

      input = {
        accel_profile = "flat",
        sensitivity   = 0,
      },

      animations = { enabled = true },
    })

    hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
    hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
    hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
    hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
    hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

    hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
    hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
    hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
    hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
    hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
    hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
    hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
    hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
    hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
    hl.animation({ leaf = "workspaces",    enabled = false })

    hl.on("hyprland.start", function()
      hl.exec_cmd("${pkgs.gnome-keyring}/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh")
    end)

    hl.bind(mod .. " + Space", hl.dsp.exec_cmd([[${pkgs.rofi}/bin/rofi -show-icons -show drun]]))
    hl.bind(mod .. " + Tab",   hl.dsp.exec_cmd([[${pkgs.dusk-keymap-switch}/bin/dusk-keymap-switch]]))

    hl.bind("Pause", hl.dsp.exec_cmd([[${pkgs.hyprlock}/bin/hyprlock]]))
    hl.bind(mod .. " + SHIFT + V", hl.dsp.exec_cmd([[bash -c "${pkgs.clipman}/bin/clipman pick -t rofi --err-on-no-selection && ${pkgs.wtype}/bin/wtype -M ctrl -M shift v"]]))

    hl.bind("SHIFT + Print", hl.dsp.exec_cmd([[${pkgs.grimblast}/bin/grimblast --notify copysave screen]]))
    hl.bind("Print",         hl.dsp.exec_cmd([[${pkgs.grimblast}/bin/grimblast --notify copysave area]]))

    hl.bind(mod .. " + Return", hl.dsp.exec_cmd([[${config.dusk.terminal.default}]]))
    hl.bind(mod .. " + B",      hl.dsp.exec_cmd([[${config.dusk.defaults.browser}]]))
    hl.bind(mod .. " + E",      hl.dsp.exec_cmd([[${pkgs.pcmanfm}/bin/pcmanfm]]))
    hl.bind(mod .. " + P",      hl.dsp.exec_cmd([[${pkgs.pinta}/bin/pinta]]))

    hl.bind(mod .. " + escape",         hl.dsp.exec_cmd([[${pkgs.swaynotificationcenter}/bin/swaync-client -op]]))
    hl.bind(mod .. " + SHIFT + escape", hl.dsp.exec_cmd([[${pkgs.swaynotificationcenter}/bin/swaync-client --close-all]]))

    hl.bind(mod .. " + C",         hl.dsp.exec_cmd([[${
      launchWeb "https://chatgpt.com" "ChatGPT" "chatgpt"
    }]]))
    hl.bind(mod .. " + D",         hl.dsp.exec_cmd([[${pkgs.discord}/bin/discord]]))
    hl.bind(mod .. " + G",         hl.dsp.exec_cmd([[${
      launchWeb "https://github.com/notifications" "Github" "github"
    }]]))
    hl.bind(mod .. " + W",         hl.dsp.exec_cmd([[${
      launchWeb "https://web.whatsapp.com" "Whatsapp Web" "whatsapp-web"
    }]]))
    hl.bind(mod .. " + X",         hl.dsp.exec_cmd([[${
      launchWeb "https://x.com/compose/post" "X" "x.com"
    }]]))
    hl.bind(mod .. " + Y",         hl.dsp.exec_cmd([[${
      launchWeb "https://www.youtube.com/feed/subscriptions" "Youtube" "youtube"
    }]]))
    hl.bind(mod .. " + SHIFT + F", hl.dsp.exec_cmd([[${
      launchWeb "https://app.fastmail.com" "Fastmail" "fastmail"
    }]]))
    hl.bind(mod .. " + SHIFT + G", hl.dsp.exec_cmd([[${launchWeb "https://grok.com" "Grok" "grok"}]]))
    hl.bind(mod .. " + SHIFT + Y", hl.dsp.exec_cmd([[${
      launchWeb "https://app.ynab.com" "You Need a Budget" "ynab"
    }]]))

    hl.bind(mod .. " + M",         hl.dsp.exec_cmd([[${config.dusk.defaults.music-player}]]))
    hl.bind(mod .. " + O",         hl.dsp.exec_cmd([[${pkgs.obsidian}/bin/obsidian]]))
    hl.bind(mod .. " + T",         hl.dsp.exec_cmd([[${pkgs.todoist-electron}/bin/todoist-electron]]))
    hl.bind(mod .. " + SHIFT + C", hl.dsp.exec_cmd([[${pkgs.gnome-calculator}/bin/gnome-calculator]]))
    hl.bind(mod .. " + SHIFT + T", hl.dsp.exec_cmd([[${pkgs.streamlink-twitch-gui-bin}/bin/streamlink-twitch-gui]]))

    hl.bind(mod .. " + CTRL + escape", hl.dsp.exec_cmd([[${pkgs.wlogout}/bin/wlogout]]))
    hl.bind(mod .. " + CTRL + A",      hl.dsp.exec_cmd([[${pkgs.pavucontrol}/bin/pavucontrol]]))
    hl.bind(mod .. " + CTRL + B",      hl.dsp.exec_cmd([[${pkgs.blueman}/bin/blueman]]))
    hl.bind(mod .. " + CTRL + D",      hl.dsp.exec_cmd([[${launchTerm "${pkgs.lazydocker}/bin/lazydocker"}]]))
    hl.bind(mod .. " + CTRL + E",      hl.dsp.exec_cmd([[${launchTerm "${pkgs.yazi}/bin/yazi"}]]))
    hl.bind(mod .. " + CTRL + N",      hl.dsp.exec_cmd([[${pkgs.networkmanagerapplet}/bin/nm-connection-editor]]))
    hl.bind(mod .. " + CTRL + P",      hl.dsp.exec_cmd([[${pkgs.crosspipe}/bin/crosspipe]]))
    hl.bind(mod .. " + CTRL + S",      hl.dsp.exec_cmd([[${launchTerm "${pkgs.btop}/bin/btop"}]]))
    hl.bind(mod .. " + CTRL + W",      hl.dsp.exec_cmd([[${launchTerm "${pkgs.nm-wifi}/bin/nm-wifi"}]]))

    ${optionalString config.dusk.system.nixos.desktop.gaming.enable ''
      hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd([[${pkgs.steam}/bin/steam]]))
    ''}

    hl.bind(mod .. " + h", hl.dsp.focus({ direction = "left" }))
    hl.bind(mod .. " + j", hl.dsp.focus({ direction = "down" }))
    hl.bind(mod .. " + k", hl.dsp.focus({ direction = "up" }))
    hl.bind(mod .. " + l", hl.dsp.focus({ direction = "right" }))

    hl.bind(mod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
    hl.bind(mod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))
    hl.bind(mod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
    hl.bind(mod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))

    hl.bind(mod .. " + SHIFT + Q",     hl.dsp.exec_cmd("hyprctl kill"))
    hl.bind(mod .. " + SHIFT + Space", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mod .. " + F",             hl.dsp.window.fullscreen({ action = "toggle" }))
    hl.bind(mod .. " + Q",             hl.dsp.window.close())

    for i = 1, 9 do
      hl.bind(mod .. " + code:" .. (9 + i),         hl.dsp.focus({ workspace = i }))
      hl.bind(mod .. " + SHIFT + code:" .. (9 + i), hl.dsp.window.move({ workspace = i, follow = false }))
    end

    hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
    hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

    pcall(require, "monitors")

    ${cfg.extraLuaConfig}
  '';
in
{
  options.dusk.system.nixos.desktop.hyprland.extraLuaConfig = mkOption {
    type = types.lines;
    default = "";
    description = ''
      Extra Lua snippets appended to the generated `hyprland.lua`. Machine
      configs use this to layer host-specific binds, env vars, and workspace
      rules on top of the shared defaults.
    '';
  };

  config = mkIf cfg.enable {
    environment = {
      sessionVariables = {
        XDG_CURRENT_DESKTOP = "Hyprland";
        XDG_SESSION_DESKTOP = "Hyprland";
        HYPRCURSOR_THEME = "rose-pine-hyprcursor";
        HYPRCURSOR_SIZE = "32";
      };

      systemPackages = with pkgs; [
        dunst
        grimblast
        rofi

        hyprcursor
        rose-pine-hyprcursor
      ];
    };

    programs = {
      dconf.enable = true;

      hyprland = {
        enable = true;
        withUWSM = true;
        xwayland.enable = true;
        package = hyprlandPkgs.hyprland;
        portalPackage = hyprlandPkgs.xdg-desktop-portal-hyprland;
      };
    };

    security.pam.services = {
      hyprlock = { };
      gdm.enableGnomeKeyring = true;
      gdm-password.enableGnomeKeyring = true;
    };

    services = {
      gnome.gnome-keyring.enable = true;

      displayManager.gdm = {
        enable = true;
        autoSuspend = false;
      };
    };

    xdg.portal = {
      enable = true;
      xdgOpenUsePortal = true;

      config.hyprland.default = [
        "hyprland"
        "gtk"
        "wlr"
      ];

      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
        xdg-desktop-portal-wlr
      ];
    };

    home-manager.users.${config.dusk.username} = {
      dconf.enable = true;

      home.pointerCursor = {
        hyprcursor.enable = true;

        name = "Adwaita";
        package = pkgs.adwaita-icon-theme;
        size = 24;
        x11 = {
          enable = true;
          defaultCursor = "Adwaita";
        };
      };

      programs = {
        hyprlock.enable = true;
        rofi.enable = true;
        wlogout.enable = true;
      };

      services = {
        clipman.enable = true;
        hypridle.enable = true;
        hyprpaper = {
          enable = true;
          settings = {
            ipc = "on";
            splash = false;
          };
        };
      };

      xdg.configFile."hypr/hyprland.lua" = {
        text = luaConfig;
        onChange = ''
          (
            XDG_RUNTIME_DIR=''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
            if [[ -d "/tmp/hypr" || -d "$XDG_RUNTIME_DIR/hypr" ]]; then
              for i in $(${hyprlandPkgs.hyprland}/bin/hyprctl instances -j | ${pkgs.jq}/bin/jq ".[].instance" -r); do
                ${hyprlandPkgs.hyprland}/bin/hyprctl -i "$i" reload config-only || true
              done
            fi
          )
        '';
      };
    };
  };
}
