{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib)
    boolToString
    concatMap
    concatMapStringsSep
    concatStringsSep
    isBool
    isInt
    mapAttrsToList
    mkIf
    mkOption
    optional
    optionalString
    optionals
    range
    types
    ;

  cfg = config.dusk.system.nixos.desktop.hyprland;
  hyprlandPkgs = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system};

  mod = "SUPER";

  launchTerm = cmd: "${pkgs.ghostty}/bin/ghostty --class=com.mitchellh.ghostty.floating -e ${cmd}";
  launchWeb =
    url: name: class:
    ''${pkgs.chromium}/bin/chromium --new-window --ozone-platform="wayland" --app="${url}" --name="${name}" --class="${class}"'';

  # Render an hl.bind flag table: { locked = true; repeating = true; }
  # -> ', { locked = true, repeating = true }'. Empty attrset -> "".
  renderFlags =
    flags:
    optionalString (flags != { }) (
      ", { " + concatStringsSep ", " (mapAttrsToList (n: v: "${n} = ${boolToString v}") flags) + " }"
    );

  renderBind =
    b:
    let
      action =
        if b.dispatch != null then
          "hl.dsp.${b.dispatch}"
        else if b.exec != null then
          "hl.dsp.exec_cmd([[${b.exec}]])"
        else
          throw ''hyprland bind "${b.key}" must set either `exec` or `dispatch`'';
    in
    ''hl.bind("${b.key}", ${action}${renderFlags b.flags})'';

  # Values a window rule can carry, on both sides of the match/set split.
  ruleValue = types.oneOf [
    types.bool
    types.int
    types.str
  ];

  # Render a rule value as a Lua literal. Strings go through long brackets so
  # that regex backslashes reach Hyprland untouched, same as the exec commands.
  luaValue =
    v:
    if isBool v then
      boolToString v
    else if isInt v then
      toString v
    else
      "[[${v}]]";

  luaTable =
    attrs: "{ " + concatStringsSep ", " (mapAttrsToList (n: v: "${n} = ${luaValue v}") attrs) + " }";

  # `set` entries are siblings of `name`/`match` inside the call, not nested:
  # hl.window_rule({ name = [[x]], match = { class = [[.*]] }, float = true })
  renderWindowRule =
    r:
    let
      entries = [
        "name = ${luaValue r.name}"
      ]
      ++ optional (r.match != { }) "match = ${luaTable r.match}"
      ++ mapAttrsToList (n: v: "${n} = ${luaValue v}") r.set;
    in
    "hl.window_rule({ " + concatStringsSep ", " entries + " })";

  luaConfig = ''
    -- Generated by Nix: system/hyprland/hyprland.nix
    -- See https://wiki.hypr.land/Configuring/Start/ for the new Lua syntax.

    hl.config({
      general = {
        gaps_in     = 8,
        gaps_out    = 24,
        border_size = 3,
      },

      decoration = {
        inactive_opacity   = 0.90,
        fullscreen_opacity = 1.0,
        rounding           = 8,
        blur = {
          enabled = true,
          size    = 8,
          passes  = 2,
        },
      },

      input = {
        accel_profile = "flat",
        sensitivity   = 0,
      },

      animations = { enabled = true },
    })

    hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
    hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
    hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
    hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
    hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

    hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
    hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, bezier = "easeOutQuint" })
    hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
    hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
    hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
    hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
    hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
    hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
    hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
    hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
    hl.animation({ leaf = "workspaces",    enabled = false })

    hl.on("hyprland.start", function()
      hl.exec_cmd("${pkgs.gnome-keyring}/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh")
      ${concatMapStringsSep "\n      " (cmd: "hl.exec_cmd([[${cmd}]])") cfg.autostart}
    end)

    -- Keybindings (declared via dusk.system.nixos.desktop.hyprland.binds)
    ${concatMapStringsSep "\n    " renderBind cfg.binds}

    -- Window rules (declared via dusk.system.nixos.desktop.hyprland.windowRules)
    ${concatMapStringsSep "\n    " renderWindowRule cfg.windowRules}

    pcall(require, "monitors")

    ${cfg.extraLuaConfig}
  '';
in
{
  options.dusk.system.nixos.desktop.hyprland = {
    autostart = mkOption {
      type = types.listOf types.str;
      default = [ ];
      example = [ "nm-applet --indicator" ];
      description = ''
        Commands executed once when the Hyprland session starts. Each entry is
        emitted as an `hl.exec_cmd` call inside the `hyprland.start` handler.
      '';
    };

    binds = mkOption {
      type = types.listOf (
        types.submodule {
          options = {
            key = mkOption {
              type = types.str;
              example = "SUPER + Return";
              description = ''Key combo passed to `hl.bind`, e.g. "SUPER + Q" or "XF86AudioMute".'';
            };
            exec = mkOption {
              type = types.nullOr types.str;
              default = null;
              description = "Command run via `hl.dsp.exec_cmd`. Mutually exclusive with `dispatch`.";
            };
            dispatch = mkOption {
              type = types.nullOr types.str;
              default = null;
              example = ''window.fullscreen({ action = "toggle" })'';
              description = ''
                Raw dispatcher expression, rendered as `hl.dsp.<dispatch>`
                (e.g. `focus({ direction = "left" })`). Mutually exclusive with `exec`.
              '';
            };
            flags = mkOption {
              type = types.attrsOf types.bool;
              default = { };
              example = {
                locked = true;
                repeating = true;
              };
              description = ''
                Optional `hl.bind` flag table. Valid keys: `locked`, `repeating`,
                `release`, `transparent`, `mouse`, `longPress`.
              '';
            };
          };
        }
      );
      default = [ ];
      description = ''
        Exec keybindings contributed by desktop modules, rendered into the
        generated `hyprland.lua` as
        `hl.bind(key, hl.dsp.exec_cmd(exec), { flags })`.
      '';
    };

    windowRules = mkOption {
      type = types.listOf (
        types.submodule {
          options = {
            name = mkOption {
              type = types.str;
              example = "float-scratch-terminals";
              description = "Rule identifier, passed through to `hl.window_rule` as `name`.";
            };
            match = mkOption {
              type = types.attrsOf ruleValue;
              default = { };
              example = {
                class = "^(pavucontrol)$";
              };
              description = ''
                Window match table (`class`, `title`, `xwayland`, `floating`, ...).
                String values are regexes. An empty set matches every window.
              '';
            };
            set = mkOption {
              type = types.attrsOf ruleValue;
              example = {
                float = true;
              };
              description = ''
                Properties applied to matching windows (`float`, `size`, `center`,
                `opacity`, `suppress_event`, ...), rendered as siblings of `match`
                inside the `hl.window_rule` call.
              '';
            };
          };
        }
      );
      default = [ ];
      description = ''
        Window rules contributed by desktop modules, rendered into the generated
        `hyprland.lua` as `hl.window_rule({ name, match, <set> })`.
      '';
    };

    extraLuaConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Raw Lua appended verbatim to the generated `hyprland.lua`. Escape hatch
        for config that `autostart`/`binds` do not model (env vars, window
        rules, host-specific tweaks). Merges across all modules that set it.
      '';
    };
  };

  config = mkIf cfg.enable {
    dusk.system.nixos.desktop.hyprland.windowRules = [
      # Upstream ships this in its stock hyprland.lua and our hand-rolled config
      # never carried it over. Apps that persist a maximized window state --
      # Chromium above all, which re-requests it for every new window -- get put
      # into Hyprland's maximized fullscreen mode on open, where they cover the
      # whole workspace on top of the tiled windows instead of joining them.
      {
        name = "suppress-maximize-events";
        match.class = ".*";
        set.suppress_event = "maximize";
      }
    ];

    dusk.system.nixos.desktop.hyprland.binds = [
      # Launchers & applications
      {
        key = "${mod} + Tab";
        exec = "${pkgs.dusk-keymap-switch}/bin/dusk-keymap-switch";
      }
      {
        key = "SHIFT + Print";
        exec = "${pkgs.grimblast}/bin/grimblast --notify copysave screen";
      }
      {
        key = "Print";
        exec = "${pkgs.grimblast}/bin/grimblast --notify copysave area";
      }
      {
        key = "${mod} + Return";
        exec = config.dusk.terminal.default;
      }
      {
        key = "${mod} + B";
        exec = config.dusk.defaults.browser;
      }
      {
        key = "${mod} + E";
        exec = "${pkgs.pcmanfm}/bin/pcmanfm";
      }
      {
        key = "${mod} + P";
        exec = "${pkgs.pinta}/bin/pinta";
      }
      {
        key = "${mod} + C";
        exec = launchWeb "https://chatgpt.com" "ChatGPT" "chatgpt";
      }
      {
        key = "${mod} + D";
        exec = "${pkgs.discord}/bin/discord";
      }
      {
        key = "${mod} + G";
        exec = launchWeb "https://github.com/notifications" "Github" "github";
      }
      {
        key = "${mod} + W";
        exec = launchWeb "https://web.whatsapp.com" "Whatsapp Web" "whatsapp-web";
      }
      {
        key = "${mod} + S";
        exec = "${pkgs.slack}/bin/slack";
      }
      {
        key = "${mod} + X";
        exec = launchWeb "https://x.com/compose/post" "X" "x.com";
      }
      {
        key = "${mod} + Y";
        exec = launchWeb "https://www.youtube.com/feed/subscriptions" "Youtube" "youtube";
      }
      {
        key = "${mod} + SHIFT + F";
        exec = launchWeb "https://app.fastmail.com" "Fastmail" "fastmail";
      }
      {
        key = "${mod} + SHIFT + G";
        exec = launchWeb "https://grok.com" "Grok" "grok";
      }
      {
        key = "${mod} + SHIFT + Y";
        exec = launchWeb "https://app.ynab.com" "You Need a Budget" "ynab";
      }
      {
        key = "${mod} + M";
        exec = config.dusk.defaults.music-player;
      }
      {
        key = "${mod} + O";
        exec = "${pkgs.obsidian}/bin/obsidian";
      }
      {
        key = "${mod} + T";
        exec = "${pkgs.todoist-electron}/bin/todoist-electron";
      }
      {
        key = "${mod} + SHIFT + C";
        exec = "${pkgs.gnome-calculator}/bin/gnome-calculator";
      }
      {
        key = "${mod} + CTRL + S";
        exec = "${pkgs.localsend}/bin/localsend_app";
      }
      {
        key = "${mod} + SHIFT + T";
        exec = "${pkgs.streamlink-twitch-gui-bin}/bin/streamlink-twitch-gui";
      }
      {
        key = "${mod} + CTRL + A";
        exec = "${pkgs.pavucontrol}/bin/pavucontrol";
      }
      {
        key = "${mod} + CTRL + B";
        exec = "${pkgs.blueman}/bin/blueman";
      }
      {
        key = "${mod} + CTRL + D";
        exec = launchTerm "${pkgs.lazydocker}/bin/lazydocker";
      }
      {
        key = "${mod} + CTRL + E";
        exec = launchTerm "${pkgs.yazi}/bin/yazi";
      }
      {
        key = "${mod} + CTRL + N";
        exec = "${pkgs.networkmanagerapplet}/bin/nm-connection-editor";
      }
      {
        key = "${mod} + CTRL + P";
        exec = "${pkgs.crosspipe}/bin/crosspipe";
      }
      {
        key = "${mod} + CTRL + W";
        exec = launchTerm "${pkgs.nm-wifi}/bin/nm-wifi";
      }

      # Focus & window management
      {
        key = "${mod} + h";
        dispatch = ''focus({ direction = "left" })'';
      }
      {
        key = "${mod} + j";
        dispatch = ''focus({ direction = "down" })'';
      }
      {
        key = "${mod} + k";
        dispatch = ''focus({ direction = "up" })'';
      }
      {
        key = "${mod} + l";
        dispatch = ''focus({ direction = "right" })'';
      }
      {
        key = "${mod} + SHIFT + h";
        dispatch = ''window.move({ direction = "left" })'';
      }
      {
        key = "${mod} + SHIFT + j";
        dispatch = ''window.move({ direction = "down" })'';
      }
      {
        key = "${mod} + SHIFT + k";
        dispatch = ''window.move({ direction = "up" })'';
      }
      {
        key = "${mod} + SHIFT + l";
        dispatch = ''window.move({ direction = "right" })'';
      }
      {
        key = "${mod} + SHIFT + Q";
        exec = "hyprctl kill";
      }
      {
        key = "${mod} + SHIFT + Space";
        dispatch = ''window.float({ action = "toggle" })'';
      }
      {
        key = "${mod} + F";
        dispatch = ''window.fullscreen({ action = "toggle" })'';
      }
      {
        key = "${mod} + Q";
        dispatch = "window.close()";
      }

      # Mouse
      {
        key = "${mod} + mouse:272";
        dispatch = "window.drag()";
        flags.mouse = true;
      }
      {
        key = "${mod} + mouse:273";
        dispatch = "window.resize()";
        flags.mouse = true;
      }
    ]
    ++ optionals config.dusk.system.nixos.desktop.gaming.enable [
      {
        key = "${mod} + SHIFT + S";
        exec = "${config.programs.steam.package}/bin/steam";
      }
    ]
    # Workspaces 1-9 (keycodes 10-18): focus, and move active window to.
    ++ concatMap (i: [
      {
        key = "${mod} + code:${toString (9 + i)}";
        dispatch = "focus({ workspace = ${toString i} })";
      }
      {
        key = "${mod} + SHIFT + code:${toString (9 + i)}";
        dispatch = "window.move({ workspace = ${toString i}, follow = false })";
      }
    ]) (range 1 9);

    environment = {
      sessionVariables = {
        XDG_CURRENT_DESKTOP = "Hyprland";
        XDG_SESSION_DESKTOP = "Hyprland";
        HYPRCURSOR_THEME = "rose-pine-hyprcursor";
        HYPRCURSOR_SIZE = "32";
      };

      systemPackages = with pkgs; [
        dunst
        grimblast

        hyprcursor
        rose-pine-hyprcursor
      ];
    };

    programs = {
      dconf.enable = true;

      hyprland = {
        enable = true;
        withUWSM = true;
        xwayland.enable = true;
        package = hyprlandPkgs.hyprland;
        portalPackage = hyprlandPkgs.xdg-desktop-portal-hyprland;
      };
    };

    security.pam.services = {
      sddm.enableGnomeKeyring = true;
    };

    services = {
      gnome.gnome-keyring.enable = true;

      displayManager.sddm = {
        enable = true;
        wayland.enable = true;
      };
    };

    xdg.portal = {
      enable = true;
      xdgOpenUsePortal = true;

      config.hyprland.default = [
        "hyprland"
        "gtk"
        "wlr"
      ];

      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
        xdg-desktop-portal-wlr
      ];
    };

    home-manager.users.${config.dusk.username} = {
      dconf.enable = true;

      home.pointerCursor = {
        hyprcursor.enable = true;

        name = "Adwaita";
        package = pkgs.adwaita-icon-theme;
        size = 24;
        x11 = {
          enable = true;
          defaultCursor = "Adwaita";
        };
      };

      xdg.configFile."hypr/hyprland.lua" = {
        text = luaConfig;
        onChange = ''
          (
            XDG_RUNTIME_DIR=''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
            if [[ -d "/tmp/hypr" || -d "$XDG_RUNTIME_DIR/hypr" ]]; then
              for i in $(${hyprlandPkgs.hyprland}/bin/hyprctl instances -j | ${pkgs.jq}/bin/jq ".[].instance" -r); do
                ${hyprlandPkgs.hyprland}/bin/hyprctl -i "$i" reload config-only || true
              done
            fi
          )
        '';
      };
    };
  };
}
