# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  services.xserver.videoDrivers = [ "nvidia" ];

  boot.initrd.secrets = { "/crypto_keyfile.bin" = null; };
  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/74a0dddd-276e-4c8b-9f61-a10d7adc1782";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5faf3f90-a835-4d76-9121-05ee876a3649".device =
    "/dev/disk/by-uuid/5faf3f90-a835-4d76-9121-05ee876a3649";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/0595-97A8";
    fsType = "vfat";
  };

  swapDevices = [ ];
  networking.useDHCP = lib.mkDefault true;

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = true;
}
