name: "Build Systems"

on:
  push:

env:
  NIX_TARGET: config.system.build.toplevel

jobs:
  build:
    strategy:
      matrix:
        items:
          - os: ubuntu-latest
            parent: .#nixosConfigurations.battlecruiser
          - os: macos-latest
            parent: .#darwinConfigurations.drone
    runs-on: ${{ matrix.items.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: cachix/cachix-action@v14
        with:
          name: cfcosta-home
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/magic-nix-cache-action@v1
      - run: nix build ${{ matrix.items.parent }}."$NIX_TARGET"
