name: "Build Systems"

on:
  push:

env:
  NIX_TARGET: config.system.build.toplevel

jobs:
  build:
    strategy:
      matrix:
        items:
          - os: ubuntu-latest
            arch: x86_64-linux
            parent: .#nixosConfigurations.battlecruiser
          - os: macos-latest
            arch: aarch64-darwin
            parent: .#darwinConfigurations.drone
    name: "Build ${{ matrix.items.arch }}"
    runs-on: ${{ matrix.items.os }}
    steps:
      - uses: actions/checkout@v4

      - if: matrix.items.os == 'ubuntu-latest'
        run: sudo find /opt -maxdepth 1 -mindepth 1 '!' -path ./containerd '!' -path ./actionarchivecache '!' -path ./runner '!' -path ./runner-cache -exec rm -rf '{}' ';'

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v14
        with:
          name: cfcosta-home
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Build
        run: nix build ${{ matrix.items.parent }}."$NIX_TARGET"
