name: "Build and push to cachix"
on:
  push:

jobs:
  home-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: cfcosta-home
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#homeConfigurations.cfcosta@mothership.activationPackage

  system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: cfcosta-home
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#nixosConfigurations.mothership.config.system.build.toplevel
