name: Job - Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN" # Every sunday at midnight

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove default tooling that uses way too much space
        run: sudo rm -rf /opt/hostedtoolcache

      - name: Install Nix Daemon
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Enable Cachix
        uses: cachix/cachix-action@v14
        with:
          name: cfcosta-home
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Update Flake
        run: nix flake update

      - name: Verify the flake is still valid
        run: nix flake check

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update flake"
