name: Job - Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN" # Every sunday at midnight

env:
  NIX_TARGET: config.system.build.toplevel

jobs:
  build:
    strategy:
      matrix:
        items:
          - os: ubuntu-latest
            arch: x86_64-linux
            parent: .#nixosConfigurations.battlecruiser
    name: "Build ${{ matrix.items.arch }}"
    runs-on: ${{ matrix.items.os }}
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - if: matrix.items.os == 'ubuntu-latest'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - run: nix flake update

      - run: nix build ${{ matrix.items.parent }}."$NIX_TARGET"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update flake"
