name: Job - Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN" # Every sunday at midnight

env:
  NIX_TARGET: config.system.build.toplevel

jobs:
  build:
    strategy:
      matrix:
        items:
          - os: ubuntu-latest
            arch: x86_64-linux
            parent: .#nixosConfigurations.battlecruiser
    name: "Build ${{ matrix.items.arch }}"
    runs-on: ${{ matrix.items.os }}
    steps:
      - uses: actions/checkout@v4

      - if: matrix.items.os == 'ubuntu-latest'
        run: sudo find /opt -maxdepth 1 -mindepth 1 '!' -path ./containerd '!' -path ./actionarchivecache '!' -path ./runner '!' -path ./runner-cache -exec rm -rf '{}' ';'

      - uses: DeterminateSystems/nix-installer-action@v4

      - uses: cachix/cachix-action@v14
        with:
          name: cfcosta-home
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run Build
        run: nix build ${{ matrix.items.parent }}."$NIX_TARGET"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update flake"
