name: Job - Update Flake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * SUN" # Every sunday at midnight

jobs:
  update-cargo2nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
      - run: nix flake update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update flake"
